spring:
  datasource:
    name: javaemp  #数据库名
    url: jdbc:mysql://localhost:3306/javaemp #url
    username: root  #用户名
    password: 123qweasd  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: java_isverygood@163.com
    host: smtp.163.com
    password: 123qweasd
    default-encoding: UTF-8
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
